---
- hosts: jenkins
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - ../roles/ansible-role-firewall
    - ../roles/ansible-role-ntp
    - ../roles/ansible-role-java
    - ../roles/ansible-role-jenkins
